# Generated by Django 4.0.3 on 2022-04-02 19:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='person',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='person',
            name='last_name',
        ),
        migrations.AddField(
            model_name='person',
            name='Observaciones',
            field=models.TextField(default='', max_length=256),
        ),
        migrations.AddField(
            model_name='person',
            name='apellido_1',
            field=models.CharField(default='', max_length=256, null=True),
        ),
        migrations.AddField(
            model_name='person',
            name='apellido_2',
            field=models.CharField(default='', max_length=256, null=True),
        ),
        migrations.AddField(
            model_name='person',
            name='cargo',
            field=models.CharField(default='', max_length=256, null=True),
        ),
        migrations.AddField(
            model_name='person',
            name='cedula',
            field=models.CharField(default='', max_length=256, null=True),
        ),
        migrations.AddField(
            model_name='person',
            name='correo',
            field=models.CharField(default='', max_length=256, null=True),
        ),
        migrations.AddField(
            model_name='person',
            name='estado',
            field=models.CharField(default='', max_length=256, null=True),
        ),
        migrations.AddField(
            model_name='person',
            name='estado_cargo',
            field=models.CharField(default='', max_length=256, null=True),
        ),
        migrations.AddField(
            model_name='person',
            name='municipio',
            field=models.CharField(default='', max_length=256, null=True),
        ),
        migrations.AddField(
            model_name='person',
            name='municipio_cargo',
            field=models.CharField(default='', max_length=256, null=True),
        ),
        migrations.AddField(
            model_name='person',
            name='nac',
            field=models.CharField(default='V', max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='person',
            name='nombre_1',
            field=models.CharField(default='', max_length=256, null=True),
        ),
        migrations.AddField(
            model_name='person',
            name='nombre_2',
            field=models.CharField(default='', max_length=256, null=True),
        ),
        migrations.AddField(
            model_name='person',
            name='nombre_tipo_equipo',
            field=models.CharField(default='', max_length=256, null=True),
        ),
        migrations.AddField(
            model_name='person',
            name='parroquia',
            field=models.CharField(default='', max_length=256, null=True),
        ),
        migrations.AddField(
            model_name='person',
            name='parroquia_cargo',
            field=models.CharField(default='', max_length=256, null=True),
        ),
        migrations.AddField(
            model_name='person',
            name='red_name',
            field=models.CharField(default='', max_length=256, null=True),
        ),
        migrations.AddField(
            model_name='person',
            name='sexo',
            field=models.CharField(default='', max_length=256, null=True),
        ),
        migrations.AddField(
            model_name='person',
            name='tlf_1',
            field=models.CharField(default='', max_length=256, null=True),
        ),
        migrations.AddField(
            model_name='person',
            name='tlf_2',
            field=models.CharField(default='', max_length=256, null=True),
        ),
        migrations.AddField(
            model_name='person',
            name='tlf_3',
            field=models.CharField(default='', max_length=256, null=True),
        ),
    ]
