# Generated by Django 4.0.3 on 2022-04-02 19:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_remove_person_first_name_remove_person_last_name_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='person',
            options={'verbose_name': 'Activista', 'verbose_name_plural': 'Activistas'},
        ),
        migrations.AlterField(
            model_name='person',
            name='estado',
            field=models.CharField(default='EDO. ZULIA', max_length=256, null=True),
        ),
        migrations.AlterField(
            model_name='person',
            name='municipio',
            field=models.CharField(default='MP. MARACAIBO', max_length=256, null=True),
        ),
        migrations.AlterField(
            model_name='person',
            name='nombre_tipo_equipo',
            field=models.CharField(choices=[('Equipo Parroquial de Activistas', 'Equipo Parroquial de Activistas'), ('Equipo de Centro de Votación', 'Equipo de Centro de Votación'), ('Red Popular', 'Red Popular')], default='', max_length=256, null=True),
        ),
        migrations.AlterField(
            model_name='person',
            name='parroquia',
            field=models.CharField(default='PQ. FRANCISCO EUGENIO B', max_length=256, null=True),
        ),
    ]
